# Generated by Django 2.0.4 on 2018-04-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binderizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindersetup',
            name='version',
            field=models.CharField(default='0.0.0', max_length=50),
            preserve_default=False,
        ),
    ]
